name: fhir_primitives
description: Small package containing the FHIR Primitives as they are the same in the Dart Packages.
version: 0.1.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/fhir-fli/fhir_primitives

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.1
  uuid: ^4.3.3
  yaml: ^3.1.2

dev_dependencies:
  # dart run import_sorter:main
  import_sorter: ^4.6.0
  test: ^1.25.2
